package json

const VERSION = 4242

const (
	INIT_VERSION = iota
	INIT_STARTPOD
	INIT_GETPOD_DEPRECATED
	INIT_STOPPOD_DEPRECATED
	INIT_DESTROYPOD
	INIT_RESTARTCONTAINER_DEPRECATED
	INIT_EXECCMD
	INIT_FINISHCMD_DEPRECATED
	INIT_READY
	INIT_ACK
	INIT_ERROR
	INIT_WINSIZE
	INIT_PING
	INIT_FINISHPOD_DEPRECATED
	INIT_NEXT
	INIT_WRITEFILE
	INIT_READFILE
	INIT_NEWCONTAINER
	INIT_KILLCONTAINER
	INIT_ONLINECPUMEM
	INIT_SETUPINTERFACE
	INIT_SETUPROUTE
)
