// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oci.proto

package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Spec struct {
	// Version of the Open Container Initiative Runtime Specification with which the bundle complies.
	Version string `protobuf:"bytes,1,opt,name=Version" json:"Version,omitempty"`
	// Process configures the container process.
	Process *OCIProcess `protobuf:"bytes,2,opt,name=Process" json:"Process,omitempty"`
	// Root configures the container's root filesystem.
	Root *Root `protobuf:"bytes,3,opt,name=Root" json:"Root,omitempty"`
	// Hostname configures the container's hostname.
	Hostname string `protobuf:"bytes,4,opt,name=Hostname" json:"Hostname,omitempty"`
	// Mounts configures additional mounts (on top of Root).
	Mounts []*OCIMount `protobuf:"bytes,5,rep,name=Mounts" json:"Mounts,omitempty"`
	// Hooks configures callbacks for container lifecycle events.
	Hooks *Hooks `protobuf:"bytes,6,opt,name=Hooks" json:"Hooks,omitempty"`
	// Annotations contains arbitrary metadata for the container.
	Annotations map[string]string `protobuf:"bytes,7,rep,name=Annotations" json:"Annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Linux is platform-specific configuration for Linux based containers.
	Linux *Linux `protobuf:"bytes,8,opt,name=Linux" json:"Linux,omitempty"`
	// Solaris is platform-specific configuration for Solaris based containers.
	Solaris *Solaris `protobuf:"bytes,9,opt,name=Solaris" json:"Solaris,omitempty"`
	// Windows is platform-specific configuration for Windows based containers.
	Windows *Windows `protobuf:"bytes,10,opt,name=Windows" json:"Windows,omitempty"`
}

func (m *Spec) Reset()                    { *m = Spec{} }
func (m *Spec) String() string            { return proto.CompactTextString(m) }
func (*Spec) ProtoMessage()               {}
func (*Spec) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Spec) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Spec) GetProcess() *OCIProcess {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *Spec) GetRoot() *Root {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *Spec) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Spec) GetMounts() []*OCIMount {
	if m != nil {
		return m.Mounts
	}
	return nil
}

func (m *Spec) GetHooks() *Hooks {
	if m != nil {
		return m.Hooks
	}
	return nil
}

func (m *Spec) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *Spec) GetLinux() *Linux {
	if m != nil {
		return m.Linux
	}
	return nil
}

func (m *Spec) GetSolaris() *Solaris {
	if m != nil {
		return m.Solaris
	}
	return nil
}

func (m *Spec) GetWindows() *Windows {
	if m != nil {
		return m.Windows
	}
	return nil
}

type OCIProcess struct {
	// Terminal creates an interactive terminal for the container.
	Terminal bool `protobuf:"varint,1,opt,name=Terminal" json:"Terminal,omitempty"`
	// ConsoleSize specifies the size of the console.
	ConsoleSize *Box `protobuf:"bytes,2,opt,name=ConsoleSize" json:"ConsoleSize,omitempty"`
	// OCIUser specifies user information for the process.
	User *OCIUser `protobuf:"bytes,3,opt,name=User" json:"User,omitempty"`
	// Args specifies the binary and arguments for the application to execute.
	Args []string `protobuf:"bytes,4,rep,name=Args" json:"Args,omitempty"`
	// Env populates the process environment for the process.
	Env []string `protobuf:"bytes,5,rep,name=Env" json:"Env,omitempty"`
	// Cwd is the current working directory for the process and must be
	// relative to the container's root.
	Cwd string `protobuf:"bytes,6,opt,name=Cwd" json:"Cwd,omitempty"`
	// Capabilities are Linux capabilities that are kept for the process.
	Capabilities *LinuxCapabilities `protobuf:"bytes,7,opt,name=Capabilities" json:"Capabilities,omitempty"`
	// Rlimits specifies rlimit options to apply to the process.
	Rlimits []*POSIXRlimit `protobuf:"bytes,8,rep,name=Rlimits" json:"Rlimits,omitempty"`
	// NoNewPrivileges controls whether additional privileges could be gained by processes in the container.
	NoNewPrivileges bool `protobuf:"varint,9,opt,name=NoNewPrivileges" json:"NoNewPrivileges,omitempty"`
	// ApparmorProfile specifies the apparmor profile for the container.
	ApparmorProfile string `protobuf:"bytes,10,opt,name=ApparmorProfile" json:"ApparmorProfile,omitempty"`
	// Specify an oom_score_adj for the container.
	OOMScoreAdj uint32 `protobuf:"varint,11,opt,name=OOMScoreAdj" json:"OOMScoreAdj,omitempty"`
	// SelinuxLabel specifies the selinux context that the container process is run as.
	SelinuxLabel string `protobuf:"bytes,12,opt,name=SelinuxLabel" json:"SelinuxLabel,omitempty"`
}

func (m *OCIProcess) Reset()                    { *m = OCIProcess{} }
func (m *OCIProcess) String() string            { return proto.CompactTextString(m) }
func (*OCIProcess) ProtoMessage()               {}
func (*OCIProcess) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *OCIProcess) GetTerminal() bool {
	if m != nil {
		return m.Terminal
	}
	return false
}

func (m *OCIProcess) GetConsoleSize() *Box {
	if m != nil {
		return m.ConsoleSize
	}
	return nil
}

func (m *OCIProcess) GetUser() *OCIUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *OCIProcess) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *OCIProcess) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *OCIProcess) GetCwd() string {
	if m != nil {
		return m.Cwd
	}
	return ""
}

func (m *OCIProcess) GetCapabilities() *LinuxCapabilities {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *OCIProcess) GetRlimits() []*POSIXRlimit {
	if m != nil {
		return m.Rlimits
	}
	return nil
}

func (m *OCIProcess) GetNoNewPrivileges() bool {
	if m != nil {
		return m.NoNewPrivileges
	}
	return false
}

func (m *OCIProcess) GetApparmorProfile() string {
	if m != nil {
		return m.ApparmorProfile
	}
	return ""
}

func (m *OCIProcess) GetOOMScoreAdj() uint32 {
	if m != nil {
		return m.OOMScoreAdj
	}
	return 0
}

func (m *OCIProcess) GetSelinuxLabel() string {
	if m != nil {
		return m.SelinuxLabel
	}
	return ""
}

type Box struct {
	// Height is the vertical dimension of a box.
	Height uint32 `protobuf:"varint,1,opt,name=Height" json:"Height,omitempty"`
	// Width is the horizontal dimension of a box.
	Width uint32 `protobuf:"varint,2,opt,name=Width" json:"Width,omitempty"`
}

func (m *Box) Reset()                    { *m = Box{} }
func (m *Box) String() string            { return proto.CompactTextString(m) }
func (*Box) ProtoMessage()               {}
func (*Box) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Box) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Box) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

type OCIUser struct {
	// UID is the user id.
	UID uint32 `protobuf:"varint,1,opt,name=UID" json:"UID,omitempty"`
	// GID is the group id.
	GID uint32 `protobuf:"varint,2,opt,name=GID" json:"GID,omitempty"`
	// AdditionalGids are additional group ids set for the container's process.
	AdditionalGids []uint32 `protobuf:"varint,3,rep,packed,name=AdditionalGids" json:"AdditionalGids,omitempty"`
	// Username is the user name.
	Username string `protobuf:"bytes,4,opt,name=Username" json:"Username,omitempty"`
}

func (m *OCIUser) Reset()                    { *m = OCIUser{} }
func (m *OCIUser) String() string            { return proto.CompactTextString(m) }
func (*OCIUser) ProtoMessage()               {}
func (*OCIUser) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *OCIUser) GetUID() uint32 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *OCIUser) GetGID() uint32 {
	if m != nil {
		return m.GID
	}
	return 0
}

func (m *OCIUser) GetAdditionalGids() []uint32 {
	if m != nil {
		return m.AdditionalGids
	}
	return nil
}

func (m *OCIUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type LinuxCapabilities struct {
	// Bounding is the set of capabilities checked by the kernel.
	Bounding []string `protobuf:"bytes,1,rep,name=Bounding" json:"Bounding,omitempty"`
	// Effective is the set of capabilities checked by the kernel.
	Effective []string `protobuf:"bytes,2,rep,name=Effective" json:"Effective,omitempty"`
	// Inheritable is the capabilities preserved across execve.
	Inheritable []string `protobuf:"bytes,3,rep,name=Inheritable" json:"Inheritable,omitempty"`
	// Permitted is the limiting superset for effective capabilities.
	Permitted []string `protobuf:"bytes,4,rep,name=Permitted" json:"Permitted,omitempty"`
	// Ambient is the ambient set of capabilities that are kept.
	Ambient []string `protobuf:"bytes,5,rep,name=Ambient" json:"Ambient,omitempty"`
}

func (m *LinuxCapabilities) Reset()                    { *m = LinuxCapabilities{} }
func (m *LinuxCapabilities) String() string            { return proto.CompactTextString(m) }
func (*LinuxCapabilities) ProtoMessage()               {}
func (*LinuxCapabilities) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *LinuxCapabilities) GetBounding() []string {
	if m != nil {
		return m.Bounding
	}
	return nil
}

func (m *LinuxCapabilities) GetEffective() []string {
	if m != nil {
		return m.Effective
	}
	return nil
}

func (m *LinuxCapabilities) GetInheritable() []string {
	if m != nil {
		return m.Inheritable
	}
	return nil
}

func (m *LinuxCapabilities) GetPermitted() []string {
	if m != nil {
		return m.Permitted
	}
	return nil
}

func (m *LinuxCapabilities) GetAmbient() []string {
	if m != nil {
		return m.Ambient
	}
	return nil
}

type POSIXRlimit struct {
	// Type of the rlimit to set
	Type string `protobuf:"bytes,1,opt,name=Type" json:"Type,omitempty"`
	// Hard is the hard limit for the specified type
	Hard uint64 `protobuf:"varint,2,opt,name=Hard" json:"Hard,omitempty"`
	// Soft is the soft limit for the specified type
	Soft uint64 `protobuf:"varint,3,opt,name=Soft" json:"Soft,omitempty"`
}

func (m *POSIXRlimit) Reset()                    { *m = POSIXRlimit{} }
func (m *POSIXRlimit) String() string            { return proto.CompactTextString(m) }
func (*POSIXRlimit) ProtoMessage()               {}
func (*POSIXRlimit) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *POSIXRlimit) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *POSIXRlimit) GetHard() uint64 {
	if m != nil {
		return m.Hard
	}
	return 0
}

func (m *POSIXRlimit) GetSoft() uint64 {
	if m != nil {
		return m.Soft
	}
	return 0
}

type OCIMount struct {
	// destination is the path inside the container expect when it starts with "tmp:/"
	Destination string `protobuf:"bytes,1,opt,name=destination" json:"destination,omitempty"`
	// source is the path inside the container expect when it starts with "vm:/dev/" or "tmp:/"
	// the path which starts with "vm:/dev/" refers the guest vm's "/dev",
	// especially, "vm:/dev/hostfs/" refers to the shared filesystem.
	// "tmp:/" is a temporary directory which is used for temporary mounts.
	Source  string   `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	Type    string   `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Options []string `protobuf:"bytes,4,rep,name=options" json:"options,omitempty"`
}

func (m *OCIMount) Reset()                    { *m = OCIMount{} }
func (m *OCIMount) String() string            { return proto.CompactTextString(m) }
func (*OCIMount) ProtoMessage()               {}
func (*OCIMount) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *OCIMount) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *OCIMount) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *OCIMount) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *OCIMount) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

type Root struct {
	// Path is the absolute path to the container's root filesystem.
	Path string `protobuf:"bytes,1,opt,name=Path" json:"Path,omitempty"`
	// Readonly makes the root filesystem for the container readonly before the process is executed.
	Readonly bool `protobuf:"varint,2,opt,name=Readonly" json:"Readonly,omitempty"`
}

func (m *Root) Reset()                    { *m = Root{} }
func (m *Root) String() string            { return proto.CompactTextString(m) }
func (*Root) ProtoMessage()               {}
func (*Root) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *Root) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Root) GetReadonly() bool {
	if m != nil {
		return m.Readonly
	}
	return false
}

type Hooks struct {
	// Prestart is a list of hooks to be run before the container process is executed.
	Prestart []*Hook `protobuf:"bytes,1,rep,name=Prestart" json:"Prestart,omitempty"`
	// Poststart is a list of hooks to be run after the container process is started.
	Poststart []*Hook `protobuf:"bytes,2,rep,name=Poststart" json:"Poststart,omitempty"`
	// Poststop is a list of hooks to be run after the container process exits.
	Poststop []*Hook `protobuf:"bytes,3,rep,name=Poststop" json:"Poststop,omitempty"`
}

func (m *Hooks) Reset()                    { *m = Hooks{} }
func (m *Hooks) String() string            { return proto.CompactTextString(m) }
func (*Hooks) ProtoMessage()               {}
func (*Hooks) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *Hooks) GetPrestart() []*Hook {
	if m != nil {
		return m.Prestart
	}
	return nil
}

func (m *Hooks) GetPoststart() []*Hook {
	if m != nil {
		return m.Poststart
	}
	return nil
}

func (m *Hooks) GetPoststop() []*Hook {
	if m != nil {
		return m.Poststop
	}
	return nil
}

type Hook struct {
	Path    string   `protobuf:"bytes,1,opt,name=Path" json:"Path,omitempty"`
	Args    []string `protobuf:"bytes,2,rep,name=Args" json:"Args,omitempty"`
	Env     []string `protobuf:"bytes,3,rep,name=Env" json:"Env,omitempty"`
	Timeout int64    `protobuf:"varint,4,opt,name=Timeout" json:"Timeout,omitempty"`
}

func (m *Hook) Reset()                    { *m = Hook{} }
func (m *Hook) String() string            { return proto.CompactTextString(m) }
func (*Hook) ProtoMessage()               {}
func (*Hook) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *Hook) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Hook) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Hook) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Hook) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type Linux struct {
	// UIDMapping specifies user mappings for supporting user namespaces.
	UIDMappings []*LinuxIDMapping `protobuf:"bytes,1,rep,name=UIDMappings" json:"UIDMappings,omitempty"`
	// GIDMapping specifies group mappings for supporting user namespaces.
	GIDMappings []*LinuxIDMapping `protobuf:"bytes,2,rep,name=GIDMappings" json:"GIDMappings,omitempty"`
	// Sysctl are a set of key value pairs that are set for the container on start
	Sysctl map[string]string `protobuf:"bytes,3,rep,name=Sysctl" json:"Sysctl,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Resources contain cgroup information for handling resource constraints
	// for the container
	Resources *LinuxResources `protobuf:"bytes,4,opt,name=Resources" json:"Resources,omitempty"`
	// CgroupsPath specifies the path to cgroups that are created and/or joined by the container.
	// The path is expected to be relative to the cgroups mountpoint.
	// If resources are specified, the cgroups at CgroupsPath will be updated based on resources.
	CgroupsPath string `protobuf:"bytes,5,opt,name=CgroupsPath" json:"CgroupsPath,omitempty"`
	// Namespaces contains the namespaces that are created and/or joined by the container
	Namespaces []*LinuxNamespace `protobuf:"bytes,6,rep,name=Namespaces" json:"Namespaces,omitempty"`
	// Devices are a list of device nodes that are created for the container
	Devices []*LinuxDevice `protobuf:"bytes,7,rep,name=Devices" json:"Devices,omitempty"`
	// Seccomp specifies the seccomp security settings for the container.
	Seccomp *LinuxSeccomp `protobuf:"bytes,8,opt,name=Seccomp" json:"Seccomp,omitempty"`
	// RootfsPropagation is the rootfs mount propagation mode for the container.
	RootfsPropagation string `protobuf:"bytes,9,opt,name=RootfsPropagation" json:"RootfsPropagation,omitempty"`
	// MaskedPaths masks over the provided paths inside the container.
	MaskedPaths []string `protobuf:"bytes,10,rep,name=MaskedPaths" json:"MaskedPaths,omitempty"`
	// ReadonlyPaths sets the provided paths as RO inside the container.
	ReadonlyPaths []string `protobuf:"bytes,11,rep,name=ReadonlyPaths" json:"ReadonlyPaths,omitempty"`
	// MountLabel specifies the selinux context for the mounts in the container.
	MountLabel string `protobuf:"bytes,12,opt,name=MountLabel" json:"MountLabel,omitempty"`
	// IntelRdt contains Intel Resource Director Technology (RDT) information
	// for handling resource constraints (e.g., L3 cache) for the container
	IntelRdt *LinuxIntelRdt `protobuf:"bytes,13,opt,name=IntelRdt" json:"IntelRdt,omitempty"`
}

func (m *Linux) Reset()                    { *m = Linux{} }
func (m *Linux) String() string            { return proto.CompactTextString(m) }
func (*Linux) ProtoMessage()               {}
func (*Linux) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *Linux) GetUIDMappings() []*LinuxIDMapping {
	if m != nil {
		return m.UIDMappings
	}
	return nil
}

func (m *Linux) GetGIDMappings() []*LinuxIDMapping {
	if m != nil {
		return m.GIDMappings
	}
	return nil
}

func (m *Linux) GetSysctl() map[string]string {
	if m != nil {
		return m.Sysctl
	}
	return nil
}

func (m *Linux) GetResources() *LinuxResources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *Linux) GetCgroupsPath() string {
	if m != nil {
		return m.CgroupsPath
	}
	return ""
}

func (m *Linux) GetNamespaces() []*LinuxNamespace {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

func (m *Linux) GetDevices() []*LinuxDevice {
	if m != nil {
		return m.Devices
	}
	return nil
}

func (m *Linux) GetSeccomp() *LinuxSeccomp {
	if m != nil {
		return m.Seccomp
	}
	return nil
}

func (m *Linux) GetRootfsPropagation() string {
	if m != nil {
		return m.RootfsPropagation
	}
	return ""
}

func (m *Linux) GetMaskedPaths() []string {
	if m != nil {
		return m.MaskedPaths
	}
	return nil
}

func (m *Linux) GetReadonlyPaths() []string {
	if m != nil {
		return m.ReadonlyPaths
	}
	return nil
}

func (m *Linux) GetMountLabel() string {
	if m != nil {
		return m.MountLabel
	}
	return ""
}

func (m *Linux) GetIntelRdt() *LinuxIntelRdt {
	if m != nil {
		return m.IntelRdt
	}
	return nil
}

type Windows struct {
	// Dummy string, never used.
	Dummy string `protobuf:"bytes,1,opt,name=dummy" json:"dummy,omitempty"`
}

func (m *Windows) Reset()                    { *m = Windows{} }
func (m *Windows) String() string            { return proto.CompactTextString(m) }
func (*Windows) ProtoMessage()               {}
func (*Windows) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *Windows) GetDummy() string {
	if m != nil {
		return m.Dummy
	}
	return ""
}

type Solaris struct {
	// Dummy string, never used.
	Dummy string `protobuf:"bytes,1,opt,name=dummy" json:"dummy,omitempty"`
}

func (m *Solaris) Reset()                    { *m = Solaris{} }
func (m *Solaris) String() string            { return proto.CompactTextString(m) }
func (*Solaris) ProtoMessage()               {}
func (*Solaris) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *Solaris) GetDummy() string {
	if m != nil {
		return m.Dummy
	}
	return ""
}

type LinuxIDMapping struct {
	// HostID is the starting UID/GID on the host to be mapped to 'ContainerID'
	HostID uint32 `protobuf:"varint,1,opt,name=HostID" json:"HostID,omitempty"`
	// ContainerID is the starting UID/GID in the container
	ContainerID uint32 `protobuf:"varint,2,opt,name=ContainerID" json:"ContainerID,omitempty"`
	// Size is the number of IDs to be mapped
	Size uint32 `protobuf:"varint,3,opt,name=Size" json:"Size,omitempty"`
}

func (m *LinuxIDMapping) Reset()                    { *m = LinuxIDMapping{} }
func (m *LinuxIDMapping) String() string            { return proto.CompactTextString(m) }
func (*LinuxIDMapping) ProtoMessage()               {}
func (*LinuxIDMapping) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *LinuxIDMapping) GetHostID() uint32 {
	if m != nil {
		return m.HostID
	}
	return 0
}

func (m *LinuxIDMapping) GetContainerID() uint32 {
	if m != nil {
		return m.ContainerID
	}
	return 0
}

func (m *LinuxIDMapping) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type LinuxNamespace struct {
	// Type is the type of namespace
	Type string `protobuf:"bytes,1,opt,name=Type" json:"Type,omitempty"`
	// Path is a path to an existing namespace persisted on disk that can be joined
	// and is of the same type
	Path string `protobuf:"bytes,2,opt,name=Path" json:"Path,omitempty"`
}

func (m *LinuxNamespace) Reset()                    { *m = LinuxNamespace{} }
func (m *LinuxNamespace) String() string            { return proto.CompactTextString(m) }
func (*LinuxNamespace) ProtoMessage()               {}
func (*LinuxNamespace) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *LinuxNamespace) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *LinuxNamespace) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type LinuxDevice struct {
	// Path to the device.
	Path string `protobuf:"bytes,1,opt,name=Path" json:"Path,omitempty"`
	// Device type, block, char, etc.
	Type string `protobuf:"bytes,2,opt,name=Type" json:"Type,omitempty"`
	// Major is the device's major number.
	Major int64 `protobuf:"varint,3,opt,name=Major" json:"Major,omitempty"`
	// Minor is the device's minor number.
	Minor int64 `protobuf:"varint,4,opt,name=Minor" json:"Minor,omitempty"`
	// FileMode permission bits for the device.
	FileMode uint32 `protobuf:"varint,5,opt,name=FileMode" json:"FileMode,omitempty"`
	// UID of the device.
	UID uint32 `protobuf:"varint,6,opt,name=UID" json:"UID,omitempty"`
	// Gid of the device.
	GID uint32 `protobuf:"varint,7,opt,name=GID" json:"GID,omitempty"`
}

func (m *LinuxDevice) Reset()                    { *m = LinuxDevice{} }
func (m *LinuxDevice) String() string            { return proto.CompactTextString(m) }
func (*LinuxDevice) ProtoMessage()               {}
func (*LinuxDevice) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *LinuxDevice) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *LinuxDevice) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *LinuxDevice) GetMajor() int64 {
	if m != nil {
		return m.Major
	}
	return 0
}

func (m *LinuxDevice) GetMinor() int64 {
	if m != nil {
		return m.Minor
	}
	return 0
}

func (m *LinuxDevice) GetFileMode() uint32 {
	if m != nil {
		return m.FileMode
	}
	return 0
}

func (m *LinuxDevice) GetUID() uint32 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *LinuxDevice) GetGID() uint32 {
	if m != nil {
		return m.GID
	}
	return 0
}

type LinuxResources struct {
	// Devices configures the device whitelist.
	Devices []*LinuxDeviceCgroup `protobuf:"bytes,1,rep,name=Devices" json:"Devices,omitempty"`
	// Memory restriction configuration
	Memory *LinuxMemory `protobuf:"bytes,2,opt,name=Memory" json:"Memory,omitempty"`
	// CPU resource restriction configuration
	CPU *LinuxCPU `protobuf:"bytes,3,opt,name=CPU" json:"CPU,omitempty"`
	// Task resource restriction configuration.
	Pids *LinuxPids `protobuf:"bytes,4,opt,name=Pids" json:"Pids,omitempty"`
	// BlockIO restriction configuration
	BlockIO *LinuxBlockIO `protobuf:"bytes,5,opt,name=BlockIO" json:"BlockIO,omitempty"`
	// Hugetlb limit (in bytes)
	HugepageLimits []*LinuxHugepageLimit `protobuf:"bytes,6,rep,name=HugepageLimits" json:"HugepageLimits,omitempty"`
	// Network restriction configuration
	Network *LinuxNetwork `protobuf:"bytes,7,opt,name=Network" json:"Network,omitempty"`
}

func (m *LinuxResources) Reset()                    { *m = LinuxResources{} }
func (m *LinuxResources) String() string            { return proto.CompactTextString(m) }
func (*LinuxResources) ProtoMessage()               {}
func (*LinuxResources) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *LinuxResources) GetDevices() []*LinuxDeviceCgroup {
	if m != nil {
		return m.Devices
	}
	return nil
}

func (m *LinuxResources) GetMemory() *LinuxMemory {
	if m != nil {
		return m.Memory
	}
	return nil
}

func (m *LinuxResources) GetCPU() *LinuxCPU {
	if m != nil {
		return m.CPU
	}
	return nil
}

func (m *LinuxResources) GetPids() *LinuxPids {
	if m != nil {
		return m.Pids
	}
	return nil
}

func (m *LinuxResources) GetBlockIO() *LinuxBlockIO {
	if m != nil {
		return m.BlockIO
	}
	return nil
}

func (m *LinuxResources) GetHugepageLimits() []*LinuxHugepageLimit {
	if m != nil {
		return m.HugepageLimits
	}
	return nil
}

func (m *LinuxResources) GetNetwork() *LinuxNetwork {
	if m != nil {
		return m.Network
	}
	return nil
}

type LinuxMemory struct {
	// Memory limit (in bytes).
	Limit int64 `protobuf:"varint,1,opt,name=Limit" json:"Limit,omitempty"`
	// Memory reservation or soft_limit (in bytes).
	Reservation int64 `protobuf:"varint,2,opt,name=Reservation" json:"Reservation,omitempty"`
	// Total memory limit (memory + swap).
	Swap int64 `protobuf:"varint,3,opt,name=Swap" json:"Swap,omitempty"`
	// Kernel memory limit (in bytes).
	Kernel int64 `protobuf:"varint,4,opt,name=Kernel" json:"Kernel,omitempty"`
	// Kernel memory limit for tcp (in bytes)
	KernelTCP int64 `protobuf:"varint,5,opt,name=KernelTCP" json:"KernelTCP,omitempty"`
	// How aggressive the kernel will swap memory pages.
	Swappiness uint64 `protobuf:"varint,6,opt,name=Swappiness" json:"Swappiness,omitempty"`
	// DisableOOMKiller disables the OOM killer for out of memory conditions
	DisableOOMKiller bool `protobuf:"varint,7,opt,name=DisableOOMKiller" json:"DisableOOMKiller,omitempty"`
}

func (m *LinuxMemory) Reset()                    { *m = LinuxMemory{} }
func (m *LinuxMemory) String() string            { return proto.CompactTextString(m) }
func (*LinuxMemory) ProtoMessage()               {}
func (*LinuxMemory) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *LinuxMemory) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *LinuxMemory) GetReservation() int64 {
	if m != nil {
		return m.Reservation
	}
	return 0
}

func (m *LinuxMemory) GetSwap() int64 {
	if m != nil {
		return m.Swap
	}
	return 0
}

func (m *LinuxMemory) GetKernel() int64 {
	if m != nil {
		return m.Kernel
	}
	return 0
}

func (m *LinuxMemory) GetKernelTCP() int64 {
	if m != nil {
		return m.KernelTCP
	}
	return 0
}

func (m *LinuxMemory) GetSwappiness() uint64 {
	if m != nil {
		return m.Swappiness
	}
	return 0
}

func (m *LinuxMemory) GetDisableOOMKiller() bool {
	if m != nil {
		return m.DisableOOMKiller
	}
	return false
}

type LinuxCPU struct {
	// CPU shares (relative weight (ratio) vs. other cgroups with cpu shares).
	Shares uint64 `protobuf:"varint,1,opt,name=Shares" json:"Shares,omitempty"`
	// CPU hardcap limit (in usecs). Allowed cpu time in a given period.
	Quota int64 `protobuf:"varint,2,opt,name=Quota" json:"Quota,omitempty"`
	// CPU period to be used for hardcapping (in usecs).
	Period uint64 `protobuf:"varint,3,opt,name=Period" json:"Period,omitempty"`
	// How much time realtime scheduling may use (in usecs).
	RealtimeRuntime int64 `protobuf:"varint,4,opt,name=RealtimeRuntime" json:"RealtimeRuntime,omitempty"`
	// CPU period to be used for realtime scheduling (in usecs).
	RealtimePeriod uint64 `protobuf:"varint,5,opt,name=RealtimePeriod" json:"RealtimePeriod,omitempty"`
	// CPUs to use within the cpuset. Default is to use any CPU available.
	Cpus string `protobuf:"bytes,6,opt,name=Cpus" json:"Cpus,omitempty"`
	// List of memory nodes in the cpuset. Default is to use any available memory node.
	Mems string `protobuf:"bytes,7,opt,name=Mems" json:"Mems,omitempty"`
}

func (m *LinuxCPU) Reset()                    { *m = LinuxCPU{} }
func (m *LinuxCPU) String() string            { return proto.CompactTextString(m) }
func (*LinuxCPU) ProtoMessage()               {}
func (*LinuxCPU) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *LinuxCPU) GetShares() uint64 {
	if m != nil {
		return m.Shares
	}
	return 0
}

func (m *LinuxCPU) GetQuota() int64 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *LinuxCPU) GetPeriod() uint64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *LinuxCPU) GetRealtimeRuntime() int64 {
	if m != nil {
		return m.RealtimeRuntime
	}
	return 0
}

func (m *LinuxCPU) GetRealtimePeriod() uint64 {
	if m != nil {
		return m.RealtimePeriod
	}
	return 0
}

func (m *LinuxCPU) GetCpus() string {
	if m != nil {
		return m.Cpus
	}
	return ""
}

func (m *LinuxCPU) GetMems() string {
	if m != nil {
		return m.Mems
	}
	return ""
}

type LinuxWeightDevice struct {
	// Major is the device's major number.
	Major int64 `protobuf:"varint,1,opt,name=Major" json:"Major,omitempty"`
	// Minor is the device's minor number.
	Minor int64 `protobuf:"varint,2,opt,name=Minor" json:"Minor,omitempty"`
	// Weight is the bandwidth rate for the device.
	Weight uint32 `protobuf:"varint,3,opt,name=Weight" json:"Weight,omitempty"`
	// LeafWeight is the bandwidth rate for the device while competing with the cgroup's child cgroups, CFQ scheduler only
	LeafWeight uint32 `protobuf:"varint,4,opt,name=LeafWeight" json:"LeafWeight,omitempty"`
}

func (m *LinuxWeightDevice) Reset()                    { *m = LinuxWeightDevice{} }
func (m *LinuxWeightDevice) String() string            { return proto.CompactTextString(m) }
func (*LinuxWeightDevice) ProtoMessage()               {}
func (*LinuxWeightDevice) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *LinuxWeightDevice) GetMajor() int64 {
	if m != nil {
		return m.Major
	}
	return 0
}

func (m *LinuxWeightDevice) GetMinor() int64 {
	if m != nil {
		return m.Minor
	}
	return 0
}

func (m *LinuxWeightDevice) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *LinuxWeightDevice) GetLeafWeight() uint32 {
	if m != nil {
		return m.LeafWeight
	}
	return 0
}

type LinuxThrottleDevice struct {
	// Major is the device's major number.
	Major int64 `protobuf:"varint,1,opt,name=Major" json:"Major,omitempty"`
	// Minor is the device's minor number.
	Minor int64 `protobuf:"varint,2,opt,name=Minor" json:"Minor,omitempty"`
	// Rate is the IO rate limit per cgroup per device
	Rate uint64 `protobuf:"varint,3,opt,name=Rate" json:"Rate,omitempty"`
}

func (m *LinuxThrottleDevice) Reset()                    { *m = LinuxThrottleDevice{} }
func (m *LinuxThrottleDevice) String() string            { return proto.CompactTextString(m) }
func (*LinuxThrottleDevice) ProtoMessage()               {}
func (*LinuxThrottleDevice) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

func (m *LinuxThrottleDevice) GetMajor() int64 {
	if m != nil {
		return m.Major
	}
	return 0
}

func (m *LinuxThrottleDevice) GetMinor() int64 {
	if m != nil {
		return m.Minor
	}
	return 0
}

func (m *LinuxThrottleDevice) GetRate() uint64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type LinuxBlockIO struct {
	// Specifies per cgroup weight
	Weight uint32 `protobuf:"varint,1,opt,name=Weight" json:"Weight,omitempty"`
	// Specifies tasks' weight in the given cgroup while competing with the cgroup's child cgroups, CFQ scheduler only
	LeafWeight uint32 `protobuf:"varint,2,opt,name=LeafWeight" json:"LeafWeight,omitempty"`
	// Weight per cgroup per device, can override BlkioWeight
	WeightDevice []*LinuxWeightDevice `protobuf:"bytes,3,rep,name=WeightDevice" json:"WeightDevice,omitempty"`
	// IO read rate limit per cgroup per device, bytes per second
	ThrottleReadBpsDevice []*LinuxThrottleDevice `protobuf:"bytes,4,rep,name=ThrottleReadBpsDevice" json:"ThrottleReadBpsDevice,omitempty"`
	// IO write rate limit per cgroup per device, bytes per second
	ThrottleWriteBpsDevice []*LinuxThrottleDevice `protobuf:"bytes,5,rep,name=ThrottleWriteBpsDevice" json:"ThrottleWriteBpsDevice,omitempty"`
	// IO read rate limit per cgroup per device, IO per second
	ThrottleReadIOPSDevice []*LinuxThrottleDevice `protobuf:"bytes,6,rep,name=ThrottleReadIOPSDevice" json:"ThrottleReadIOPSDevice,omitempty"`
	// IO write rate limit per cgroup per device, IO per second
	ThrottleWriteIOPSDevice []*LinuxThrottleDevice `protobuf:"bytes,7,rep,name=ThrottleWriteIOPSDevice" json:"ThrottleWriteIOPSDevice,omitempty"`
}

func (m *LinuxBlockIO) Reset()                    { *m = LinuxBlockIO{} }
func (m *LinuxBlockIO) String() string            { return proto.CompactTextString(m) }
func (*LinuxBlockIO) ProtoMessage()               {}
func (*LinuxBlockIO) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{21} }

func (m *LinuxBlockIO) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *LinuxBlockIO) GetLeafWeight() uint32 {
	if m != nil {
		return m.LeafWeight
	}
	return 0
}

func (m *LinuxBlockIO) GetWeightDevice() []*LinuxWeightDevice {
	if m != nil {
		return m.WeightDevice
	}
	return nil
}

func (m *LinuxBlockIO) GetThrottleReadBpsDevice() []*LinuxThrottleDevice {
	if m != nil {
		return m.ThrottleReadBpsDevice
	}
	return nil
}

func (m *LinuxBlockIO) GetThrottleWriteBpsDevice() []*LinuxThrottleDevice {
	if m != nil {
		return m.ThrottleWriteBpsDevice
	}
	return nil
}

func (m *LinuxBlockIO) GetThrottleReadIOPSDevice() []*LinuxThrottleDevice {
	if m != nil {
		return m.ThrottleReadIOPSDevice
	}
	return nil
}

func (m *LinuxBlockIO) GetThrottleWriteIOPSDevice() []*LinuxThrottleDevice {
	if m != nil {
		return m.ThrottleWriteIOPSDevice
	}
	return nil
}

type LinuxPids struct {
	// Maximum number of PIDs. Default is "no limit".
	Limit int64 `protobuf:"varint,1,opt,name=Limit" json:"Limit,omitempty"`
}

func (m *LinuxPids) Reset()                    { *m = LinuxPids{} }
func (m *LinuxPids) String() string            { return proto.CompactTextString(m) }
func (*LinuxPids) ProtoMessage()               {}
func (*LinuxPids) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{22} }

func (m *LinuxPids) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type LinuxDeviceCgroup struct {
	// Allow or deny
	Allow bool `protobuf:"varint,1,opt,name=Allow" json:"Allow,omitempty"`
	// Device type, block, char, etc.
	Type string `protobuf:"bytes,2,opt,name=Type" json:"Type,omitempty"`
	// Major is the device's major number.
	Major int64 `protobuf:"varint,3,opt,name=Major" json:"Major,omitempty"`
	// Minor is the device's minor number.
	Minor int64 `protobuf:"varint,4,opt,name=Minor" json:"Minor,omitempty"`
	// Cgroup access permissions format, rwm.
	Access string `protobuf:"bytes,5,opt,name=Access" json:"Access,omitempty"`
}

func (m *LinuxDeviceCgroup) Reset()                    { *m = LinuxDeviceCgroup{} }
func (m *LinuxDeviceCgroup) String() string            { return proto.CompactTextString(m) }
func (*LinuxDeviceCgroup) ProtoMessage()               {}
func (*LinuxDeviceCgroup) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{23} }

func (m *LinuxDeviceCgroup) GetAllow() bool {
	if m != nil {
		return m.Allow
	}
	return false
}

func (m *LinuxDeviceCgroup) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *LinuxDeviceCgroup) GetMajor() int64 {
	if m != nil {
		return m.Major
	}
	return 0
}

func (m *LinuxDeviceCgroup) GetMinor() int64 {
	if m != nil {
		return m.Minor
	}
	return 0
}

func (m *LinuxDeviceCgroup) GetAccess() string {
	if m != nil {
		return m.Access
	}
	return ""
}

type LinuxNetwork struct {
	// Set class identifier for container's network packets
	ClassID uint32 `protobuf:"varint,1,opt,name=ClassID" json:"ClassID,omitempty"`
	// Set priority of network traffic for container
	Priorities []*LinuxInterfacePriority `protobuf:"bytes,2,rep,name=Priorities" json:"Priorities,omitempty"`
}

func (m *LinuxNetwork) Reset()                    { *m = LinuxNetwork{} }
func (m *LinuxNetwork) String() string            { return proto.CompactTextString(m) }
func (*LinuxNetwork) ProtoMessage()               {}
func (*LinuxNetwork) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{24} }

func (m *LinuxNetwork) GetClassID() uint32 {
	if m != nil {
		return m.ClassID
	}
	return 0
}

func (m *LinuxNetwork) GetPriorities() []*LinuxInterfacePriority {
	if m != nil {
		return m.Priorities
	}
	return nil
}

type LinuxHugepageLimit struct {
	// Pagesize is the hugepage size
	Pagesize string `protobuf:"bytes,1,opt,name=Pagesize" json:"Pagesize,omitempty"`
	// Limit is the limit of "hugepagesize" hugetlb usage
	Limit uint64 `protobuf:"varint,2,opt,name=Limit" json:"Limit,omitempty"`
}

func (m *LinuxHugepageLimit) Reset()                    { *m = LinuxHugepageLimit{} }
func (m *LinuxHugepageLimit) String() string            { return proto.CompactTextString(m) }
func (*LinuxHugepageLimit) ProtoMessage()               {}
func (*LinuxHugepageLimit) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{25} }

func (m *LinuxHugepageLimit) GetPagesize() string {
	if m != nil {
		return m.Pagesize
	}
	return ""
}

func (m *LinuxHugepageLimit) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type LinuxInterfacePriority struct {
	// Name is the name of the network interface
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	// Priority for the interface
	Priority uint32 `protobuf:"varint,2,opt,name=Priority" json:"Priority,omitempty"`
}

func (m *LinuxInterfacePriority) Reset()                    { *m = LinuxInterfacePriority{} }
func (m *LinuxInterfacePriority) String() string            { return proto.CompactTextString(m) }
func (*LinuxInterfacePriority) ProtoMessage()               {}
func (*LinuxInterfacePriority) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{26} }

func (m *LinuxInterfacePriority) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LinuxInterfacePriority) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type LinuxSeccomp struct {
	DefaultAction string          `protobuf:"bytes,1,opt,name=DefaultAction" json:"DefaultAction,omitempty"`
	Architectures []string        `protobuf:"bytes,2,rep,name=Architectures" json:"Architectures,omitempty"`
	Syscalls      []*LinuxSyscall `protobuf:"bytes,3,rep,name=Syscalls" json:"Syscalls,omitempty"`
}

func (m *LinuxSeccomp) Reset()                    { *m = LinuxSeccomp{} }
func (m *LinuxSeccomp) String() string            { return proto.CompactTextString(m) }
func (*LinuxSeccomp) ProtoMessage()               {}
func (*LinuxSeccomp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{27} }

func (m *LinuxSeccomp) GetDefaultAction() string {
	if m != nil {
		return m.DefaultAction
	}
	return ""
}

func (m *LinuxSeccomp) GetArchitectures() []string {
	if m != nil {
		return m.Architectures
	}
	return nil
}

func (m *LinuxSeccomp) GetSyscalls() []*LinuxSyscall {
	if m != nil {
		return m.Syscalls
	}
	return nil
}

type LinuxSeccompArg struct {
	Index    uint64 `protobuf:"varint,1,opt,name=Index" json:"Index,omitempty"`
	Value    uint64 `protobuf:"varint,2,opt,name=Value" json:"Value,omitempty"`
	ValueTwo uint64 `protobuf:"varint,3,opt,name=ValueTwo" json:"ValueTwo,omitempty"`
	Op       string `protobuf:"bytes,4,opt,name=Op" json:"Op,omitempty"`
}

func (m *LinuxSeccompArg) Reset()                    { *m = LinuxSeccompArg{} }
func (m *LinuxSeccompArg) String() string            { return proto.CompactTextString(m) }
func (*LinuxSeccompArg) ProtoMessage()               {}
func (*LinuxSeccompArg) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{28} }

func (m *LinuxSeccompArg) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *LinuxSeccompArg) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *LinuxSeccompArg) GetValueTwo() uint64 {
	if m != nil {
		return m.ValueTwo
	}
	return 0
}

func (m *LinuxSeccompArg) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

type LinuxSyscall struct {
	Names  []string           `protobuf:"bytes,1,rep,name=Names" json:"Names,omitempty"`
	Action string             `protobuf:"bytes,2,opt,name=Action" json:"Action,omitempty"`
	Args   []*LinuxSeccompArg `protobuf:"bytes,3,rep,name=Args" json:"Args,omitempty"`
}

func (m *LinuxSyscall) Reset()                    { *m = LinuxSyscall{} }
func (m *LinuxSyscall) String() string            { return proto.CompactTextString(m) }
func (*LinuxSyscall) ProtoMessage()               {}
func (*LinuxSyscall) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{29} }

func (m *LinuxSyscall) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *LinuxSyscall) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *LinuxSyscall) GetArgs() []*LinuxSeccompArg {
	if m != nil {
		return m.Args
	}
	return nil
}

type LinuxIntelRdt struct {
	// The schema for L3 cache id and capacity bitmask (CBM)
	// Format: "L3:<cache_id0>=<cbm0>;<cache_id1>=<cbm1>;..."
	L3CacheSchema string `protobuf:"bytes,1,opt,name=L3CacheSchema" json:"L3CacheSchema,omitempty"`
}

func (m *LinuxIntelRdt) Reset()                    { *m = LinuxIntelRdt{} }
func (m *LinuxIntelRdt) String() string            { return proto.CompactTextString(m) }
func (*LinuxIntelRdt) ProtoMessage()               {}
func (*LinuxIntelRdt) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{30} }

func (m *LinuxIntelRdt) GetL3CacheSchema() string {
	if m != nil {
		return m.L3CacheSchema
	}
	return ""
}

func init() {
	proto.RegisterType((*Spec)(nil), "grpc.Spec")
	proto.RegisterType((*OCIProcess)(nil), "grpc.OCIProcess")
	proto.RegisterType((*Box)(nil), "grpc.Box")
	proto.RegisterType((*OCIUser)(nil), "grpc.OCIUser")
	proto.RegisterType((*LinuxCapabilities)(nil), "grpc.LinuxCapabilities")
	proto.RegisterType((*POSIXRlimit)(nil), "grpc.POSIXRlimit")
	proto.RegisterType((*OCIMount)(nil), "grpc.OCIMount")
	proto.RegisterType((*Root)(nil), "grpc.Root")
	proto.RegisterType((*Hooks)(nil), "grpc.Hooks")
	proto.RegisterType((*Hook)(nil), "grpc.Hook")
	proto.RegisterType((*Linux)(nil), "grpc.Linux")
	proto.RegisterType((*Windows)(nil), "grpc.Windows")
	proto.RegisterType((*Solaris)(nil), "grpc.Solaris")
	proto.RegisterType((*LinuxIDMapping)(nil), "grpc.LinuxIDMapping")
	proto.RegisterType((*LinuxNamespace)(nil), "grpc.LinuxNamespace")
	proto.RegisterType((*LinuxDevice)(nil), "grpc.LinuxDevice")
	proto.RegisterType((*LinuxResources)(nil), "grpc.LinuxResources")
	proto.RegisterType((*LinuxMemory)(nil), "grpc.LinuxMemory")
	proto.RegisterType((*LinuxCPU)(nil), "grpc.LinuxCPU")
	proto.RegisterType((*LinuxWeightDevice)(nil), "grpc.LinuxWeightDevice")
	proto.RegisterType((*LinuxThrottleDevice)(nil), "grpc.LinuxThrottleDevice")
	proto.RegisterType((*LinuxBlockIO)(nil), "grpc.LinuxBlockIO")
	proto.RegisterType((*LinuxPids)(nil), "grpc.LinuxPids")
	proto.RegisterType((*LinuxDeviceCgroup)(nil), "grpc.LinuxDeviceCgroup")
	proto.RegisterType((*LinuxNetwork)(nil), "grpc.LinuxNetwork")
	proto.RegisterType((*LinuxHugepageLimit)(nil), "grpc.LinuxHugepageLimit")
	proto.RegisterType((*LinuxInterfacePriority)(nil), "grpc.LinuxInterfacePriority")
	proto.RegisterType((*LinuxSeccomp)(nil), "grpc.LinuxSeccomp")
	proto.RegisterType((*LinuxSeccompArg)(nil), "grpc.LinuxSeccompArg")
	proto.RegisterType((*LinuxSyscall)(nil), "grpc.LinuxSyscall")
	proto.RegisterType((*LinuxIntelRdt)(nil), "grpc.LinuxIntelRdt")
}

func init() { proto.RegisterFile("oci.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1942 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0x4b, 0x73, 0x1b, 0xc7,
	0x11, 0x2e, 0x3c, 0x88, 0x47, 0x43, 0xa0, 0xc4, 0xb1, 0x4c, 0x6f, 0x14, 0x97, 0x43, 0x6d, 0x5c,
	0x0a, 0xfd, 0x28, 0xba, 0x22, 0x25, 0x2e, 0xe7, 0x59, 0x01, 0x41, 0x59, 0x44, 0x99, 0x14, 0xe0,
	0x01, 0x69, 0xa5, 0x72, 0x48, 0xd5, 0x72, 0x31, 0x04, 0xc6, 0x5c, 0xec, 0x6c, 0x66, 0x07, 0xa4,
	0x98, 0x5b, 0xae, 0xb9, 0xe5, 0x27, 0xe4, 0x94, 0x3f, 0x90, 0xff, 0x90, 0xaa, 0x5c, 0x72, 0xc8,
	0x31, 0x7f, 0x26, 0xd5, 0x3d, 0xb3, 0x8b, 0x01, 0x40, 0xd9, 0x79, 0x9c, 0x30, 0xfd, 0x75, 0x4f,
	0xcf, 0xf4, 0xf4, 0x73, 0x01, 0x6d, 0x15, 0xcb, 0x83, 0x4c, 0x2b, 0xa3, 0x58, 0x7d, 0xaa, 0xb3,
	0x38, 0xfc, 0x5b, 0x0d, 0xea, 0xe3, 0x4c, 0xc4, 0x2c, 0x80, 0xe6, 0x57, 0x42, 0xe7, 0x52, 0xa5,
	0x41, 0x65, 0xaf, 0xb2, 0xdf, 0xe6, 0x05, 0xc9, 0x3e, 0x84, 0xe6, 0x48, 0xab, 0x58, 0xe4, 0x79,
	0x50, 0xdd, 0xab, 0xec, 0x77, 0x9e, 0x3e, 0x38, 0xc0, 0xad, 0x07, 0xc3, 0xfe, 0xc0, 0xe1, 0xbc,
	0x10, 0x60, 0xef, 0x41, 0x9d, 0x2b, 0x65, 0x82, 0x1a, 0x09, 0x82, 0x15, 0x44, 0x84, 0x13, 0xce,
	0x1e, 0x41, 0xeb, 0x58, 0xe5, 0x26, 0x8d, 0xe6, 0x22, 0xa8, 0xd3, 0x31, 0x25, 0xcd, 0x9e, 0x40,
	0xe3, 0x54, 0x2d, 0x52, 0x93, 0x07, 0x5b, 0x7b, 0xb5, 0xfd, 0xce, 0xd3, 0xed, 0xf2, 0x18, 0x82,
	0xb9, 0xe3, 0xb2, 0xc7, 0xb0, 0x75, 0xac, 0xd4, 0x55, 0x1e, 0x34, 0xe8, 0x90, 0x8e, 0x15, 0x23,
	0x88, 0x5b, 0x0e, 0xfb, 0x05, 0x74, 0x7a, 0x69, 0xaa, 0x4c, 0x64, 0xa4, 0x4a, 0xf3, 0xa0, 0x49,
	0xfa, 0xbe, 0x6b, 0x05, 0xd1, 0xda, 0x03, 0x8f, 0xfb, 0x3c, 0x35, 0xfa, 0x96, 0xfb, 0xf2, 0x78,
	0xc2, 0x89, 0x4c, 0x17, 0xaf, 0x83, 0x96, 0x7f, 0x02, 0x41, 0xdc, 0x72, 0xd8, 0x0f, 0xa0, 0x39,
	0x56, 0x49, 0xa4, 0x65, 0x1e, 0xb4, 0x49, 0xa8, 0xeb, 0xb4, 0x5b, 0x90, 0x17, 0x5c, 0x14, 0x7c,
	0x25, 0xd3, 0x89, 0xba, 0xc9, 0x03, 0xf0, 0x05, 0x1d, 0xc8, 0x0b, 0xee, 0xa3, 0x5f, 0xc2, 0x83,
	0xf5, 0x5b, 0xb1, 0x07, 0x50, 0xbb, 0x12, 0xb7, 0xce, 0x21, 0xb8, 0x64, 0x0f, 0x61, 0xeb, 0x3a,
	0x4a, 0x16, 0x82, 0x5c, 0xd1, 0xe6, 0x96, 0xf8, 0x69, 0xf5, 0xb3, 0x4a, 0xf8, 0xd7, 0x1a, 0xc0,
	0xd2, 0x25, 0xf8, 0xd2, 0x67, 0x42, 0xcf, 0x65, 0x1a, 0x25, 0xb4, 0xbf, 0xc5, 0x4b, 0x9a, 0x7d,
	0x04, 0x9d, 0xbe, 0x4a, 0x73, 0x95, 0x88, 0xb1, 0xfc, 0xbd, 0x70, 0x5e, 0x6d, 0xdb, 0x7b, 0x1d,
	0xaa, 0xd7, 0xdc, 0xe7, 0xb2, 0xc7, 0x50, 0x3f, 0xcf, 0x85, 0x76, 0x2e, 0xed, 0x96, 0x4e, 0x41,
	0x90, 0x13, 0x8b, 0x31, 0xa8, 0xf7, 0xf4, 0x34, 0x0f, 0xea, 0x7b, 0xb5, 0xfd, 0x36, 0xa7, 0x35,
	0x5e, 0xfd, 0x79, 0x7a, 0x4d, 0xae, 0x6c, 0x73, 0x5c, 0x22, 0xd2, 0xbf, 0x99, 0x90, 0xd7, 0xda,
	0x1c, 0x97, 0xec, 0x67, 0x70, 0xaf, 0x1f, 0x65, 0xd1, 0x85, 0x4c, 0xa4, 0x91, 0x02, 0xfd, 0x84,
	0x47, 0xbc, 0xe3, 0x3d, 0xb7, 0xcf, 0xe6, 0x2b, 0xc2, 0xec, 0x23, 0x68, 0xf2, 0x44, 0xce, 0xa5,
	0xc9, 0x83, 0x16, 0xf9, 0x77, 0xc7, 0xee, 0x1b, 0x0d, 0xc7, 0x83, 0x5f, 0x5b, 0x0e, 0x2f, 0x24,
	0xd8, 0x3e, 0xdc, 0x7f, 0xa9, 0x5e, 0x8a, 0x9b, 0x91, 0x96, 0xd7, 0x32, 0x11, 0x53, 0x61, 0xdd,
	0xd6, 0xe2, 0xeb, 0x30, 0x4a, 0xf6, 0xb2, 0x2c, 0xd2, 0x73, 0xa5, 0x47, 0x5a, 0x5d, 0xca, 0x44,
	0x90, 0xdf, 0xda, 0x7c, 0x1d, 0x66, 0x7b, 0xd0, 0x19, 0x0e, 0x4f, 0xc7, 0xb1, 0xd2, 0xa2, 0x37,
	0xf9, 0x3a, 0xe8, 0xec, 0x55, 0xf6, 0xbb, 0xdc, 0x87, 0x58, 0x08, 0xf7, 0xc6, 0x22, 0x41, 0x3b,
	0x4e, 0xa2, 0x0b, 0x91, 0x04, 0xf7, 0x48, 0xd1, 0x0a, 0x16, 0x3e, 0x83, 0xda, 0xa1, 0x7a, 0xcd,
	0x76, 0xa1, 0x71, 0x2c, 0xe4, 0x74, 0x66, 0xc8, 0x59, 0x5d, 0xee, 0x28, 0xf4, 0xf7, 0x2b, 0x39,
	0x31, 0x33, 0x72, 0x52, 0x97, 0x5b, 0x22, 0xfc, 0x1d, 0x34, 0x9d, 0x07, 0xf0, 0x55, 0xcf, 0x07,
	0x47, 0x6e, 0x17, 0x2e, 0x11, 0x79, 0x31, 0x38, 0x72, 0x1b, 0x70, 0xc9, 0x9e, 0xc0, 0x76, 0x6f,
	0x32, 0x91, 0x18, 0x58, 0x51, 0xf2, 0x42, 0x4e, 0xf2, 0xa0, 0xb6, 0x57, 0xdb, 0xef, 0xf2, 0x35,
	0x14, 0x63, 0x06, 0x75, 0xfa, 0xd9, 0x59, 0xd0, 0xe1, 0x5f, 0x2a, 0xb0, 0xb3, 0xe1, 0x12, 0xdc,
	0x71, 0xa8, 0x16, 0xe9, 0x44, 0xa6, 0xd3, 0xa0, 0x42, 0xae, 0x2e, 0x69, 0xf6, 0x2e, 0xb4, 0x9f,
	0x5f, 0x5e, 0x8a, 0xd8, 0xc8, 0x6b, 0x8c, 0x31, 0x64, 0x2e, 0x01, 0x7c, 0xbd, 0x41, 0x3a, 0x13,
	0x5a, 0x9a, 0xe8, 0x22, 0x11, 0x74, 0xa1, 0x36, 0xf7, 0x21, 0xdc, 0x3f, 0xc2, 0x88, 0x35, 0x46,
	0x4c, 0x5c, 0x68, 0x2d, 0x01, 0xac, 0x57, 0xbd, 0xf9, 0x85, 0x14, 0xa9, 0x71, 0x31, 0x56, 0x90,
	0xe1, 0x00, 0x3a, 0x5e, 0x0c, 0x60, 0x70, 0x9e, 0xdd, 0x66, 0xc2, 0x25, 0x11, 0xad, 0x11, 0x3b,
	0x8e, 0xf4, 0x84, 0xde, 0xa8, 0xce, 0x69, 0x8d, 0xd8, 0x58, 0x5d, 0xda, 0xd2, 0x55, 0xe7, 0xb4,
	0x0e, 0x35, 0xb4, 0x8a, 0xf2, 0x83, 0x17, 0x9e, 0x88, 0xdc, 0xc8, 0x94, 0x12, 0xd4, 0xa9, 0xf3,
	0x21, 0xf4, 0x61, 0xae, 0x16, 0x3a, 0x2e, 0x92, 0xd3, 0x51, 0xa8, 0xd9, 0xe0, 0x0d, 0x6a, 0xf6,
	0x06, 0xb8, 0xc6, 0xeb, 0xab, 0xcc, 0x56, 0x27, 0x6b, 0x5a, 0x41, 0x86, 0x9f, 0xda, 0x12, 0x8a,
	0xbb, 0x46, 0x91, 0x99, 0x15, 0xf7, 0xc6, 0x35, 0x3e, 0x37, 0x17, 0xd1, 0x44, 0xa5, 0xc9, 0x2d,
	0x9d, 0xd1, 0xe2, 0x25, 0x1d, 0xfe, 0xa1, 0xe2, 0xea, 0x22, 0x7b, 0x02, 0xad, 0x91, 0x16, 0xb9,
	0x89, 0xb4, 0x21, 0xa7, 0x94, 0x85, 0x18, 0xd9, 0xbc, 0xe4, 0xb1, 0x7d, 0x68, 0x8f, 0x54, 0x6e,
	0xac, 0x60, 0x75, 0x43, 0x70, 0xc9, 0x24, 0x8d, 0x44, 0xa8, 0x8c, 0x3c, 0xb5, 0xae, 0xd1, 0xf1,
	0xc2, 0xdf, 0x40, 0x1d, 0x91, 0x3b, 0xef, 0x5e, 0x14, 0x89, 0xea, 0x66, 0x91, 0xa8, 0x2d, 0x8b,
	0x44, 0x00, 0xcd, 0x33, 0x39, 0x17, 0x6a, 0x61, 0x28, 0x02, 0x6b, 0xbc, 0x20, 0xc3, 0x3f, 0x6d,
	0xb9, 0xaa, 0xcc, 0x3e, 0x85, 0xce, 0xf9, 0xe0, 0xe8, 0x34, 0xca, 0x32, 0x99, 0x4e, 0x73, 0x67,
	0xe2, 0x43, 0xaf, 0x6a, 0x94, 0x4c, 0xee, 0x0b, 0xe2, 0xbe, 0x17, 0xde, 0xbe, 0xea, 0x37, 0xed,
	0xf3, 0x04, 0xd9, 0x27, 0xd0, 0x18, 0xdf, 0xe6, 0xb1, 0x49, 0x9c, 0xed, 0x7e, 0x81, 0x3a, 0xb0,
	0x1c, 0xdb, 0x44, 0x9c, 0x18, 0x7b, 0x0a, 0x6d, 0x2e, 0xac, 0xf3, 0x73, 0x32, 0x63, 0xf5, 0x98,
	0x92, 0xc7, 0x97, 0x62, 0x18, 0x5e, 0xfd, 0xa9, 0x56, 0x8b, 0x2c, 0xa7, 0x97, 0xdb, 0xb2, 0xe1,
	0xe5, 0x41, 0xec, 0x47, 0x00, 0x2f, 0xa3, 0xb9, 0xc8, 0xb3, 0x08, 0xd5, 0x36, 0x36, 0x6e, 0x5f,
	0x32, 0xb9, 0x27, 0x87, 0x65, 0xf2, 0x48, 0x5c, 0xcb, 0x58, 0x14, 0x6d, 0x70, 0xc7, 0xdb, 0x62,
	0x39, 0xbc, 0x90, 0x60, 0x1f, 0x43, 0x73, 0x2c, 0xe2, 0x58, 0xcd, 0x33, 0xd7, 0xfa, 0x98, 0x27,
	0xec, 0x38, 0xbc, 0x10, 0x61, 0x1f, 0xc3, 0x0e, 0x46, 0xea, 0x65, 0x3e, 0xd2, 0x2a, 0x8b, 0xa6,
	0x36, 0x2f, 0xda, 0x74, 0xf1, 0x4d, 0x06, 0x1a, 0x78, 0x1a, 0xe5, 0x57, 0x62, 0x82, 0xc6, 0x60,
	0x33, 0xa4, 0x84, 0xf7, 0x20, 0xf6, 0x3e, 0x74, 0x8b, 0x68, 0xb6, 0x32, 0x1d, 0x92, 0x59, 0x05,
	0xd9, 0x7b, 0x00, 0x94, 0x90, 0x7e, 0x49, 0xf5, 0x10, 0xf6, 0x09, 0xb4, 0x06, 0xa9, 0x11, 0x09,
	0x9f, 0x98, 0xa0, 0x4b, 0x46, 0xbc, 0xe5, 0xbb, 0xd8, 0xb1, 0x78, 0x29, 0xf4, 0xe8, 0x27, 0xd0,
	0xf1, 0x9c, 0xf8, 0x5f, 0xf5, 0xdc, 0xef, 0x95, 0xcd, 0x1d, 0x85, 0x26, 0x8b, 0xf9, 0xbc, 0xd8,
	0x68, 0x09, 0x14, 0x28, 0x06, 0x81, 0xbb, 0x05, 0x7e, 0x0b, 0xdb, 0xab, 0xa1, 0x47, 0x9d, 0x40,
	0xe5, 0xa6, 0xac, 0xe9, 0x8e, 0xa2, 0x00, 0x51, 0xa9, 0x89, 0x64, 0x2a, 0x74, 0x59, 0xde, 0x7d,
	0x88, 0x2a, 0x18, 0xf6, 0xf3, 0x1a, 0xb1, 0x68, 0x1d, 0x7e, 0xe6, 0xf4, 0x97, 0x11, 0xf1, 0xa6,
	0x7a, 0x48, 0x51, 0x57, 0x5d, 0xe6, 0x6b, 0xf8, 0xe7, 0x0a, 0x74, 0xbc, 0x20, 0x79, 0x53, 0x4e,
	0x93, 0xae, 0xaa, 0xa7, 0xeb, 0x21, 0x6c, 0x9d, 0x46, 0x5f, 0x2b, 0x3b, 0x30, 0xd4, 0xb8, 0x25,
	0x08, 0x95, 0xa9, 0xd2, 0x2e, 0xab, 0x2d, 0x81, 0xf5, 0xec, 0x73, 0x99, 0x88, 0x53, 0x35, 0x11,
	0x14, 0xf1, 0x5d, 0x5e, 0xd2, 0x45, 0x63, 0x6b, 0x6c, 0x34, 0xb6, 0x66, 0xd9, 0xd8, 0xc2, 0x7f,
	0x56, 0x9d, 0x79, 0xcb, 0x3c, 0xfa, 0xe1, 0x32, 0xde, 0x2b, 0x1b, 0xd9, 0x6a, 0x39, 0x36, 0xa9,
	0x96, 0x51, 0xff, 0x01, 0x34, 0x4e, 0xc5, 0x5c, 0xe9, 0x5b, 0x37, 0x09, 0xf9, 0x19, 0x62, 0x19,
	0xdc, 0x09, 0xb0, 0x3d, 0xa8, 0xf5, 0x47, 0xe7, 0x6e, 0x16, 0xda, 0xf6, 0x07, 0x95, 0xd1, 0x39,
	0x47, 0x16, 0xfb, 0x3e, 0xd4, 0x47, 0xd8, 0x61, 0x6d, 0xda, 0xdf, 0xf7, 0x44, 0x10, 0xe6, 0xc4,
	0xc4, 0x3c, 0x3b, 0x4c, 0x54, 0x7c, 0x35, 0x18, 0x92, 0xd9, 0xab, 0x79, 0xe6, 0x38, 0xbc, 0x10,
	0x61, 0xbf, 0x82, 0xed, 0xe3, 0xc5, 0x54, 0x64, 0xd1, 0x54, 0x9c, 0xd8, 0x81, 0xc7, 0x26, 0x7f,
	0xe0, 0x6d, 0x5a, 0x11, 0xe0, 0x6b, 0xf2, 0x78, 0xde, 0x4b, 0x61, 0x6e, 0x94, 0xbe, 0x72, 0x33,
	0x96, 0x7f, 0x9e, 0xe3, 0xf0, 0x42, 0x24, 0xfc, 0x57, 0xe1, 0x79, 0x67, 0xf4, 0x43, 0x2c, 0xbc,
	0x73, 0x69, 0x47, 0x93, 0x1a, 0xb7, 0x04, 0xc6, 0x23, 0x17, 0xb9, 0xd0, 0xd7, 0x36, 0xef, 0xab,
	0xc4, 0xf3, 0x21, 0x8a, 0xc7, 0x9b, 0x28, 0x73, 0x81, 0x40, 0x6b, 0x8c, 0xee, 0x2f, 0x84, 0x4e,
	0x45, 0xe2, 0x02, 0xc1, 0x51, 0xd8, 0xec, 0xed, 0xea, 0xac, 0x3f, 0xa2, 0x37, 0xa9, 0xf1, 0x25,
	0x80, 0x39, 0x8f, 0xbb, 0x33, 0x99, 0xe2, 0x57, 0x48, 0x83, 0x3a, 0xb4, 0x87, 0xb0, 0x0f, 0xe1,
	0xc1, 0x91, 0xcc, 0x71, 0x6a, 0x18, 0x0e, 0x4f, 0xbf, 0x90, 0x49, 0x22, 0x34, 0x19, 0xda, 0xe2,
	0x1b, 0x78, 0xf8, 0xf7, 0x0a, 0xb4, 0x0a, 0x97, 0xe1, 0x75, 0xc6, 0xb3, 0x48, 0x53, 0xb0, 0xa0,
	0x52, 0x47, 0xa1, 0xc9, 0x5f, 0x2e, 0x94, 0x89, 0x9c, 0x59, 0x96, 0x40, 0xe9, 0x91, 0xd0, 0x52,
	0x4d, 0xdc, 0x90, 0xe0, 0x28, 0x9c, 0x19, 0xb9, 0x88, 0x12, 0x23, 0xe7, 0x82, 0x2f, 0x52, 0xfc,
	0x71, 0xd6, 0xad, 0xc3, 0x38, 0x89, 0x15, 0x90, 0xd3, 0xb4, 0x45, 0x9a, 0xd6, 0x50, 0x7c, 0xba,
	0x7e, 0xb6, 0xc8, 0xdd, 0xb0, 0x4c, 0x6b, 0xc4, 0x4e, 0xc5, 0xdc, 0x4e, 0xc9, 0x6d, 0x4e, 0xeb,
	0xf0, 0xc6, 0x0d, 0x65, 0xaf, 0x68, 0x5a, 0x74, 0x99, 0x5a, 0x66, 0x60, 0xe5, 0xce, 0x0c, 0xac,
	0xfa, 0x19, 0xb8, 0x0b, 0x0d, 0xbb, 0xd7, 0x55, 0x0d, 0x47, 0xe1, 0x8b, 0x9f, 0x88, 0xe8, 0xd2,
	0xf1, 0xea, 0xc4, 0xf3, 0x90, 0xf0, 0x1c, 0xde, 0xa2, 0x83, 0xcf, 0x66, 0x5a, 0x19, 0x93, 0x88,
	0xff, 0xe1, 0x68, 0x06, 0x75, 0x1e, 0x19, 0x51, 0x0c, 0x5c, 0xb8, 0x0e, 0xff, 0x51, 0x83, 0x7b,
	0x7e, 0x12, 0x78, 0xf7, 0xab, 0x7c, 0xc3, 0xfd, 0xaa, 0xeb, 0xf7, 0xc3, 0x4f, 0x0b, 0xff, 0x4d,
	0xee, 0xe8, 0xdc, 0x3e, 0x9b, 0xaf, 0x08, 0xb3, 0x21, 0xbc, 0x5d, 0xd8, 0x85, 0xbd, 0xe7, 0x30,
	0xcb, 0x9d, 0x96, 0x3a, 0x69, 0xf9, 0x8e, 0xa7, 0x65, 0xd5, 0x7e, 0x7e, 0xf7, 0x3e, 0xf6, 0x25,
	0xec, 0x16, 0x8c, 0x57, 0x5a, 0x1a, 0xb1, 0xd4, 0xb8, 0xf5, 0x6d, 0x1a, 0xdf, 0xb0, 0xd1, 0x57,
	0x89, 0x67, 0x0d, 0x86, 0xa3, 0xb1, 0x53, 0xd9, 0xf8, 0x8f, 0x55, 0xae, 0x6e, 0x64, 0x63, 0x78,
	0x67, 0xe5, 0x30, 0x4f, 0x67, 0xf3, 0xdb, 0x74, 0xbe, 0x69, 0x67, 0xf8, 0x18, 0xda, 0x65, 0xf5,
	0xbb, 0xbb, 0x92, 0xe0, 0xe4, 0xba, 0xb3, 0x51, 0x9e, 0x51, 0xb6, 0x97, 0x24, 0xea, 0xc6, 0x7d,
	0xbd, 0x5a, 0xe2, 0xff, 0xee, 0x38, 0xbb, 0xd0, 0xe8, 0xc5, 0xf4, 0x5f, 0x86, 0x9d, 0xb0, 0x1c,
	0x15, 0x5e, 0xba, 0xb8, 0x73, 0x35, 0x10, 0xe7, 0xd0, 0x7e, 0x12, 0xe5, 0x79, 0xd9, 0x86, 0x0b,
	0x92, 0xfd, 0x1c, 0x60, 0xa4, 0xa5, 0xd2, 0xf6, 0x93, 0xd5, 0x0e, 0x91, 0xef, 0xae, 0x4d, 0x18,
	0xfa, 0x32, 0x8a, 0x85, 0x93, 0xba, 0xe5, 0x9e, 0x7c, 0xf8, 0x39, 0xb0, 0xcd, 0x7a, 0x8d, 0x7d,
	0x70, 0x14, 0x4d, 0x45, 0x8e, 0xdd, 0xdb, 0xf6, 0xd7, 0x92, 0x5e, 0xbe, 0x99, 0xfd, 0x58, 0x71,
	0x6f, 0x76, 0x0c, 0xbb, 0x77, 0x9f, 0x86, 0x2f, 0x84, 0xcd, 0xbe, 0xe8, 0xd3, 0xb8, 0x26, 0xfd,
	0x8e, 0xef, 0x72, 0xa5, 0xa4, 0xc3, 0x3f, 0x56, 0x9c, 0xe9, 0xc5, 0x58, 0xf7, 0x3e, 0x74, 0x8f,
	0xc4, 0x65, 0xb4, 0x48, 0x4c, 0x2f, 0xf6, 0x3e, 0x75, 0x56, 0x41, 0x94, 0xea, 0xe9, 0x78, 0x26,
	0x8d, 0x88, 0xcd, 0x42, 0x8b, 0x62, 0xae, 0x5f, 0x05, 0xd9, 0x01, 0xb4, 0x70, 0xb6, 0x8a, 0x92,
	0x24, 0x77, 0x29, 0xb8, 0x32, 0x51, 0x5a, 0x16, 0x2f, 0x65, 0x42, 0x09, 0xf7, 0xfd, 0xbb, 0xf4,
	0xf4, 0x14, 0xed, 0x1f, 0xa4, 0x13, 0xf1, 0xda, 0x55, 0x68, 0x4b, 0x20, 0xfa, 0x55, 0x39, 0x93,
	0xd5, 0xb9, 0x25, 0xd0, 0x4e, 0x5a, 0x9c, 0xdd, 0x28, 0x57, 0x56, 0x4a, 0x9a, 0x6d, 0x43, 0x75,
	0x98, 0xb9, 0xcf, 0xda, 0xea, 0x30, 0x0b, 0xa7, 0x85, 0xd9, 0xf6, 0x6c, 0xd4, 0x48, 0x43, 0x92,
	0xfb, 0x8e, 0xb5, 0x84, 0x8d, 0x97, 0xb2, 0xc1, 0x51, 0xbc, 0x90, 0xf9, 0x1f, 0xb8, 0xaf, 0x19,
	0x6b, 0xd4, 0xdb, 0x9b, 0x63, 0x72, 0x4f, 0x4f, 0xed, 0x47, 0x4e, 0xf8, 0x63, 0xe8, 0xae, 0x8c,
	0x9e, 0xf8, 0x74, 0x27, 0xcf, 0xfa, 0x51, 0x3c, 0x13, 0xe3, 0x78, 0x26, 0xe6, 0x51, 0xf1, 0xc0,
	0x2b, 0xe0, 0x45, 0x83, 0xfe, 0xa6, 0x7b, 0xf6, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x5e,
	0x64, 0xf2, 0xb3, 0x13, 0x00, 0x00,
}
